// library/packages/svelte/src/payconductor/payconductor.svelte
<script context="module" lang="ts">
  export interface PayConductorEmbedProps extends PayConductorConfig {
    height?: string;
    children?: any;
    onReady?: () => void;
    onError?: (error: Error) => void;
    onPaymentComplete?: (result: PaymentResult) => void;
  }
</script>

<script lang="ts">
  import { onMount } from "svelte";

  import { IFRAME_DEFAULT_HEIGHT } from "./constants";
  import { buildIframeUrl } from "./utils";
  import {
    PayConductorConfig,
    PaymentResult,
    CreatePaymentMethodOptions,
    PayConductorState,
    PayConductorFrame,
  } from "./types";
  import {
    createPendingRequestsMap,
    createPaymentMethod,
    confirmPayment,
    validatePayment,
    resetPayment,
    handleMessageEvent,
    PendingRequest,
  } from "./internal";

  export let clientId: PayConductorEmbedProps["clientId"];
  export let token: PayConductorEmbedProps["token"];
  export let theme: PayConductorEmbedProps["theme"] = undefined;
  export let locale: PayConductorEmbedProps["locale"] = undefined;
  export let onReady: PayConductorEmbedProps["onReady"] = undefined;
  export let onError: PayConductorEmbedProps["onError"] = undefined;
  export let onPaymentComplete: PayConductorEmbedProps["onPaymentComplete"] =
    undefined;

  export let height: PayConductorEmbedProps["height"] = undefined;
  function stringifyStyles(stylesObj) {
    let styles = "";
    for (let key in stylesObj) {
      const dashedKey = key.replace(/[A-Z]/g, function (match) {
        return "-" + match.toLowerCase();
      });
      styles += dashedKey + ":" + stylesObj[key] + ";";
    }
    return styles;
  }

  let iframeRef;

  let isLoaded = false;
  let isReady = false;
  let error = null;
  let iframeUrl = "";
  let pendingMap = null;

  onMount(() => {
    iframeUrl = buildIframeUrl({
      clientId: clientId,
      token: token,
      theme: theme,
      locale: locale,
    });
    isLoaded = true;
    pendingMap = createPendingRequestsMap();
    const frame: PayConductorFrame = {
      iframe: iframeRef,
      get isReady() {
        return isReady;
      },
      get error() {
        return error;
      },
    };
    const api = {
      createPaymentMethod: (options: CreatePaymentMethodOptions) =>
        createPaymentMethod(iframeRef, pendingMap, options),
      confirmPayment: (paymentMethodId: string) =>
        confirmPayment(iframeRef, pendingMap, paymentMethodId),
      validate: (data: any) => validatePayment(iframeRef, pendingMap, data),
      reset: () => resetPayment(iframeRef, pendingMap),
    };
    window.__payConductor = {
      frame,
      config: {
        clientId: clientId,
        token: token,
        theme: theme,
        locale: locale,
      },
      api,
    };
    const eventHandler = (event: MessageEvent) => {
      handleMessageEvent(
        event,
        pendingMap,
        (val) => (isReady = val),
        (val) => (error = val),
        onReady,
        onError,
        onPaymentComplete
      );
    };
    window.addEventListener("message", eventHandler);
  });
</script>

<div
  style={stringifyStyles({
    width: "100%",
    position: "relative",
  })}
  id="payconductor"
  class="payconductor"
>
  <slot />
  {#if isLoaded}
    <iframe
      style={stringifyStyles({
        width: "100%",
        height: height || IFRAME_DEFAULT_HEIGHT,
        border: "none",
      })}
      title="PayConductor"
      allow="payment"
      bind:this={iframeRef}
      src={iframeUrl}
    />
  {/if}
</div>

// library/packages/vue/src/payconductor/payconductor.vue
<template>
  <div
    id="payconductor"
    class="payconductor"
    :style="{
      width: '100%',
      position: 'relative',
    }"
  >
    <slot />
    <template v-if="isLoaded">
      <iframe
        title="PayConductor"
        allow="payment"
        ref="iframeRef"
        :src="iframeUrl"
        :style="{
          width: '100%',
          height: height || IFRAME_DEFAULT_HEIGHT,
          border: 'none',
        }"
      ></iframe>
    </template>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import { IFRAME_DEFAULT_HEIGHT } from "./constants";
import { buildIframeUrl } from "./utils";
import {
  PayConductorConfig,
  PaymentResult,
  CreatePaymentMethodOptions,
  PayConductorState,
  PayConductorFrame,
} from "./types";
import {
  createPendingRequestsMap,
  createPaymentMethod,
  confirmPayment,
  validatePayment,
  resetPayment,
  handleMessageEvent,
  PendingRequest,
} from "./internal";

export interface PayConductorEmbedProps extends PayConductorConfig {
  height?: string;
  children?: any;
  onReady?: () => void;
  onError?: (error: Error) => void;
  onPaymentComplete?: (result: PaymentResult) => void;
}

export default defineComponent({
  name: "pay-conductor",

  props: [
    "clientId",
    "token",
    "theme",
    "locale",
    "onReady",
    "onError",
    "onPaymentComplete",
    "height",
  ],

  data() {
    return {
      isLoaded: false,
      isReady: false,
      error: null,
      iframeUrl: "",
      pendingMap: null,
      IFRAME_DEFAULT_HEIGHT,
    };
  },

  mounted() {
    this.iframeUrl = buildIframeUrl({
      clientId: this.clientId,
      token: this.token,
      theme: this.theme,
      locale: this.locale,
    });
    this.isLoaded = true;
    this.pendingMap = createPendingRequestsMap();
    const frame: PayConductorFrame = {
      iframe: this.$refs.iframeRef,
      get isReady() {
        return this.isReady;
      },
      get error() {
        return this.error;
      },
    };
    const api = {
      createPaymentMethod: (options: CreatePaymentMethodOptions) =>
        createPaymentMethod(this.$refs.iframeRef, this.pendingMap, options),
      confirmPayment: (paymentMethodId: string) =>
        confirmPayment(this.$refs.iframeRef, this.pendingMap, paymentMethodId),
      validate: (data: any) =>
        validatePayment(this.$refs.iframeRef, this.pendingMap, data),
      reset: () => resetPayment(this.$refs.iframeRef, this.pendingMap),
    };
    window.__payConductor = {
      frame,
      config: {
        clientId: this.clientId,
        token: this.token,
        theme: this.theme,
        locale: this.locale,
      },
      api,
    };
    const eventHandler = (event: MessageEvent) => {
      handleMessageEvent(
        event,
        this.pendingMap,
        (val) => (this.isReady = val),
        (val) => (this.error = val),
        this.onReady,
        this.onError,
        this.onPaymentComplete
      );
    };
    window.addEventListener("message", eventHandler);
  },
});
</script>
