// library/v1/packages/preact/src/payconductor/payconductor-element.tsx
/** @jsx h */
import { h, Fragment } from "preact";
import { useState, useRef, useEffect } from "preact/hooks";

export interface PayConductorCheckoutElementProps {
  height?: string;
}

import { IFRAME_DEFAULT_HEIGHT_VALUE } from "./constants";

function PayConductorCheckoutElement(props: PayConductorCheckoutElementProps) {
  const iframeRef = useRef<HTMLIFrameElement | Element | unknown | null>(null);
  const [iframeUrl, setIframeUrl] = useState(() => "");

  const [isLoaded, setIsLoaded] = useState(() => false);

  useEffect(() => {
    const ctx = typeof window !== "undefined" ? window.PayConductor : null;
    if (!ctx) {
      console.warn(
        "[PayConductorCheckoutElement] window.PayConductor not found — ensure <PayConductor> is mounted before <PayConductorCheckoutElement>"
      );
    }
    if (ctx?.frame) {
      setIframeUrl(ctx.frame.iframeUrl || "");
      ctx.frame.iframe = iframeRef.current;
      console.log(
        "[PayConductorCheckoutElement] iframe registered, src:",
        iframeUrl
      );
    }
    setIsLoaded(true);
  }, []);

  return (
    <div
      className="payconductor-element"
      style={{
        width: "100%",
      }}
    >
      {isLoaded &&
      iframeUrl &&
      iframeRef.current &&
      "contentWindow" in iframeRef.current ? (
        <iframe
          allow="payment"
          title="PayConductor"
          ref={iframeRef}
          src={iframeUrl}
          style={{
            width: "100%",
            height: props.height || IFRAME_DEFAULT_HEIGHT_VALUE,
            border: "none",
          }}
        />
      ) : null}
    </div>
  );
}

export default PayConductorCheckoutElement;

// library/v1/packages/solid/src/payconductor/payconductor-element.tsx
import { Show, onMount, createSignal, createMemo } from "solid-js";

export interface PayConductorCheckoutElementProps {
  height?: string;
}

import { IFRAME_DEFAULT_HEIGHT_VALUE } from "./constants";

function PayConductorCheckoutElement(props: PayConductorCheckoutElementProps) {
  const [iframeUrl, setIframeUrl] = createSignal("");

  const [isLoaded, setIsLoaded] = createSignal(false);

  let iframeRef: HTMLIFrameElement | Element | unknown | null;

  onMount(() => {
    const ctx = typeof window !== "undefined" ? window.PayConductor : null;
    if (!ctx) {
      console.warn(
        "[PayConductorCheckoutElement] window.PayConductor not found — ensure <PayConductor> is mounted before <PayConductorCheckoutElement>"
      );
    }
    if (ctx?.frame) {
      setIframeUrl(ctx.frame.iframeUrl || "");
      ctx.frame.iframe = iframeRef;
      console.log(
        "[PayConductorCheckoutElement] iframe registered, src:",
        iframeUrl()
      );
    }
    setIsLoaded(true);
  });

  return (
    <>
      <div
        class="payconductor-element"
        style={{
          width: "100%",
        }}
      >
        <Show
          when={
            isLoaded() &&
            iframeUrl() &&
            iframeRef &&
            "contentWindow" in iframeRef
          }
        >
          <iframe
            allow="payment"
            title="PayConductor"
            ref={iframeRef!}
            src={iframeUrl()}
            style={{
              width: "100%",
              height: props.height || IFRAME_DEFAULT_HEIGHT_VALUE,
              border: "none",
            }}
          ></iframe>
        </Show>
      </div>
    </>
  );
}

export default PayConductorCheckoutElement;
