// library/v1/packages/rsc/src/payconductor/payconductor-element.tsx
"use client";
import * as React from "react";
import { useState, useRef, useEffect } from "react";

export interface PayConductorCheckoutElementProps {
  height?: string;
}

import { IFRAME_DEFAULT_HEIGHT_VALUE } from "./constants";

function PayConductorCheckoutElement(props: PayConductorCheckoutElementProps) {
  const iframeRef = useRef<any>(null);
  const [iframeUrl, setIframeUrl] = useState(() => "");

  const [isLoaded, setIsLoaded] = useState(() => false);

  useEffect(() => {
    const ctx = typeof window !== "undefined" ? window.PayConductor : null;
    if (!ctx) {
      console.warn(
        "[PayConductorCheckoutElement] window.PayConductor not found — ensure <PayConductor> is mounted before <PayConductorCheckoutElement>"
      );
    }
    if (ctx?.frame) {
      setIframeUrl(ctx.frame.iframeUrl || "");
      ctx.frame.iframe = iframeRef.current;
      console.log(
        "[PayConductorCheckoutElement] iframe registered, src:",
        iframeUrl
      );
    }
    setIsLoaded(true);
  }, []);

  return (
    <div
      className="payconductor-element"
      style={{
        width: "100%",
      }}
    >
      {isLoaded &&
      iframeUrl &&
      iframeRef.current &&
      "contentWindow" in iframeRef.current ? (
        <iframe
          allow="payment"
          title="PayConductor"
          ref={iframeRef}
          src={iframeUrl}
          style={{
            width: "100%",
            height: props.height || IFRAME_DEFAULT_HEIGHT_VALUE,
            border: "none",
          }}
        />
      ) : null}
    </div>
  );
}

export default PayConductorCheckoutElement;

// library/v1/packages/vue/src/payconductor/payconductor-element.vue
<template>
  <div
    class="payconductor-element"
    :style="{
      width: '100%',
    }"
  >
    <template
      v-if="
        isLoaded &&
        iframeUrl &&
        this.$refs.iframeRef &&
        'contentWindow' in this.$refs.iframeRef
      "
    >
      <iframe
        allow="payment"
        title="PayConductor"
        ref="iframeRef"
        :src="iframeUrl"
        :style="{
          width: '100%',
          height: height || IFRAME_DEFAULT_HEIGHT_VALUE,
          border: 'none',
        }"
      ></iframe>
    </template>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import { IFRAME_DEFAULT_HEIGHT_VALUE } from "./constants";

export interface PayConductorCheckoutElementProps {
  height?: string;
}

export default defineComponent({
  name: "pay-conductor-checkout-element",

  props: ["height"],

  data() {
    return { iframeUrl: "", isLoaded: false, IFRAME_DEFAULT_HEIGHT_VALUE };
  },

  mounted() {
    const ctx = typeof window !== "undefined" ? window.PayConductor : null;
    if (!ctx) {
      console.warn(
        "[PayConductorCheckoutElement] window.PayConductor not found — ensure <PayConductor> is mounted before <PayConductorCheckoutElement>"
      );
    }
    if (ctx?.frame) {
      this.iframeUrl = ctx.frame.iframeUrl || "";
      ctx.frame.iframe = this.$refs.iframeRef;
      console.log(
        "[PayConductorCheckoutElement] iframe registered, src:",
        this.iframeUrl
      );
    }
    this.isLoaded = true;
  },
});
</script>
